# Site settings
title: Novel + Develop 
email: garshialove@naver.com
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username: noveloper

# Build settings
markdown: redcarpet
baseurl : "/blog"

comments:
  disqus: "noveloper"
#isso: "comments.mysite.org"
