# Site settings
title: Novel + Develop 
email: garshialove@naver.com
url: "http://noveloper.github.io/blog"
github_username: noveloper

# Build settings
markdown: redcarpet
baseurl : "/blog"

comments:
  disqus: "noveloper"
#isso: "comments.mysite.org"
